"""
Calculator Agent — OpenTelemetry version with AUTO-instrumentation (no Langfuse).

Extends agent.py with openinference-instrumentation-openai-agents, which
automatically captures child spans for every LLM call, tool call, and handoff
made by the OpenAI Agents SDK.

Span hierarchy produced:
  calculator-agent-run              ← manual outer span (workflow level)
    runner.run                      ← manual inner span (SDK execution level)
      [LLM call span]               ← auto-generated by OpenAIAgentsInstrumentor
      [tool call: add]              ← auto-generated by OpenAIAgentsInstrumentor
      [tool call: multiply]         ← auto-generated by OpenAIAgentsInstrumentor
      ...

MCP Servers (start first from parent Appraoch_new/ directory):
    python mcp_tool_instrumented.py add_sub   # → localhost:8081 (with OTel tracing)
    python mcp_tool_instrumented.py mul_div   # → localhost:8082 (with OTel tracing)

OTLP backend (Grafana stack with Tempo):
    cd ../grafana_stack && docker compose up -d
    Then view traces in Grafana: http://localhost:3000

Run:
    python agent_auto.py
"""

import asyncio
import logging
import os
import time
from dotenv import load_dotenv

load_dotenv()  # loads otel_agent/.env

# Silence "OPENAI_API_KEY is not set, skipping trace export" from the agents SDK.
# We use Groq, so the key is never sent anywhere — this is a dummy placeholder.
os.environ.setdefault("OPENAI_API_KEY", "not-used-routing-to-groq")

# ── 1. OTel bootstrap (MUST happen before instrumentor + agents SDK imports) ──
from otel_setup import init_otel, get_tracer, get_meter

trace_provider, metrics_provider = init_otel("calculator-agent")

tracer = get_tracer("otel_agent.agent_auto")
meter  = get_meter("otel_agent.agent_auto")
logger = logging.getLogger(__name__)

# ── 2. Auto-instrumentation ───────────────────────────────────────────────────
# IMPORTANT: instrument() must be called AFTER init_otel() sets the global
# TracerProvider, and BEFORE any Agent or Runner objects are created.
from openinference.instrumentation.openai_agents import OpenAIAgentsInstrumentor
from opentelemetry.instrumentation.httpx import HTTPXClientInstrumentor

OpenAIAgentsInstrumentor().instrument()
# MCPServerStreamableHttp uses httpx internally — this injects traceparent headers
HTTPXClientInstrumentor().instrument()

# ── 3. Metrics instruments ────────────────────────────────────────────────────
run_counter = meter.create_counter(
    "agent.runs.total",
    unit="1",
    description="Total number of calculator agent runs",
)
run_duration = meter.create_histogram(
    "agent.run.duration",
    unit="s",
    description="Wall-clock duration of each run_agent() call in seconds",
)

# ── 4. Agent + MCP setup ──────────────────────────────────────────────────────
from agents import AsyncOpenAI, OpenAIChatCompletionsModel, Agent, Runner
from agents import trace as agents_trace   # alias avoids collision with opentelemetry.trace
from agents.mcp import MCPServerStreamableHttp

client = AsyncOpenAI(
    api_key=os.environ["API_KEY"],
    base_url="https://api.groq.com/openai/v1/",
)
model = OpenAIChatCompletionsModel(
    model="openai/gpt-oss-120b",
    openai_client=client,
)

add_sub_server = MCPServerStreamableHttp(
    name="add_sub_server",
    params={"url": "http://localhost:8081/mcp"},
    cache_tools_list=True,
)
mul_div_server = MCPServerStreamableHttp(
    name="mul_div_server",
    params={"url": "http://localhost:8082/mcp"},
    cache_tools_list=True,
)

agent = Agent(
    name="CalculatorAgent",
    instructions=(
        "You are a calculator assistant. "
        "Use the add/subtract tools for addition and subtraction, "
        "and the multiply/divide tools for multiplication and division. "
        "Always use a tool to compute — never calculate mentally."
    ),
    model=model,
    mcp_servers=[add_sub_server, mul_div_server],
)

# ── 5. Traced runner ──────────────────────────────────────────────────────────
async def run_agent(user_message: str) -> str:
    """
    Run the calculator agent with OTel tracing (manual + auto).

    The outer start_as_current_span creates your manual OTel span.
    The agents_trace() context inside gives OpenAIAgentsInstrumentor the
    workflow name it uses when emitting its auto-generated child spans.
    Both layers appear as a single unified trace in your OTel backend.
    """
    start = time.perf_counter()

    with tracer.start_as_current_span("calculator-agent-run") as span:
        span.set_attribute("workflow.name", "calculator-agent-run")
        span.set_attribute("agent.input", user_message)

        logger.info(f"Agent run started: {user_message}")

        with tracer.start_as_current_span("runner.run") as inner:
            inner.set_attribute("agent.name", "CalculatorAgent")
            # agents_trace() tells OpenAIAgentsInstrumentor the workflow name;
            # its auto-generated spans (LLM calls, tool calls) become children
            # of the enclosing OTel span automatically.
            with agents_trace(workflow_name="calculator-agent-run"):
                result = await Runner.run(agent, input=user_message)

        final_output = result.final_output
        elapsed = time.perf_counter() - start

        span.set_attribute("agent.output", final_output)

        run_counter.add(1, {"agent": "CalculatorAgent"})
        run_duration.record(elapsed, {"agent": "CalculatorAgent"})

        logger.info(f"Agent run complete ({elapsed:.3f}s): {final_output}")

    return final_output

# ── 6. Entry point ────────────────────────────────────────────────────────────
async def main():
    questions = ["Solve step by step: (3 + 5) * 2 - 4 / 2"
        # "What is 42 + 58?",
        # "What is 100 - 37?",
        # "What is 6 multiplied by 9?",
        # "What is 144 divided by 12?",
        # "What is (25 + 75) * 4?",   # multi-step: uses both MCP servers
    ]

    # Wrap MCP setup + all runs in one root span so that the MCP connection
    # HTTP calls (GET/POST/DELETE) become children, not separate root traces
    with tracer.start_as_current_span("agent-session") as session_span:
        session_span.set_attribute("question.count", len(questions))

        async with add_sub_server, mul_div_server:
            await add_sub_server.list_tools()
            await mul_div_server.list_tools()

            for question in questions:
                print(f"\nUser: {question}")
                response = await run_agent(question)
                print(f"Agent: {response}")

    # Flush all pending spans and shut down metrics before exit
    trace_provider.force_flush()   # synchronous — do NOT await
    metrics_provider.shutdown()


if __name__ == "__main__":
    asyncio.run(main())
